# Generated by Django 5.1.7 on 2025-03-28 00:50

from django.db import migrations


def populate_roles(apps, schemaeditor):
    entries = {
        "developer": "The person on the team who does the work",
        "scrum master": "The team's coach",
        "product owner": "The person on the team who defines the work"
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

def populate_teams(apps, schmeaditor):
    entries = {
        "alpha": "The A team",
        "bravo": "The B team",
        "charlie": "The C team",
        "delta": "The D team"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
        migrations.RunPython(populate_teams),
    ]
